name: bac_files_admin
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1007

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter  
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  dio: ^5.6.0
  pretty_dio_logger: ^1.4.0
  flutter_secure_storage: ^9.2.2
  dartz: ^0.10.1
  mocktail: ^1.0.4
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  fluttertoast: ^8.2.8
  dotted_border: ^2.1.0
  file_picker: ^8.0.5
  syncfusion_flutter_datagrid: ^27.1.53
  receive_sharing_intent: ^1.8.0
  go_router: ^14.2.7
  open_file: ^3.5.3
  syncfusion_flutter_pdfviewer: ^27.1.53
  connectivity_plus: ^6.0.5
  rxdart: ^0.28.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  permission_handler: ^11.3.1
  flutter_background_service: ^5.0.10
  path: ^1.9.0
  path_provider: ^2.1.4
  shared_preferences: ^2.2.3
  hive_flutter: ^1.1.0
  skeletonizer: ^1.4.2
  logger: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
    
  path_provider_platform_interface: ^2.1.2  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/NotoSansArabic/
    - assets/fonts/Vazirmatn/
    - assets/images/ui/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic/NotoSansArabic-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSansArabic/NotoSansArabic-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansArabic/NotoSansArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansArabic/NotoSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansArabic/NotoSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansArabic/NotoSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansArabic/NotoSansArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansArabic/NotoSansArabic-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansArabic/NotoSansArabic-Thin.ttf
          weight: 100
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn/Vazirmatn-Black.ttf
          weight: 900
        - asset: assets/fonts/Vazirmatn/Vazirmatn-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Vazirmatn/Vazirmatn-Bold.ttf
          weight: 700
        - asset: assets/fonts/Vazirmatn/Vazirmatn-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Vazirmatn/Vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazirmatn/Vazirmatn-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vazirmatn/Vazirmatn-Light.ttf
          weight: 300
        - asset: assets/fonts/Vazirmatn/Vazirmatn-ExtraLight.ttf
          weight: 200










